# -*- coding: utf-8 -*-
"""h8dsft_converter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pzpb2uALwwoVglVq0cFWwL1S-Oo5GszT

Fathur Rachman

#Assignment Instructions

- Buatlah sebuah function yang dapat mengkonversi suhu dari kelvin ke celcius, 
dan celcius ke kelvin.
- Buatlah sebuah function yang dapat mengkonversi suhu ke fahrenheit. Tambahkan parameter untuk memastikan bahwa argumen yang dimasukan adalah celcius atau kelvin. Panggil function yang pertama jika diperlukan.
- Buatlah sebuah function yang dapat mengkonversi suhu dari fahrenheit. Berikan argumen untuk memastikan bahwa outputnya dalah celcius atau kelvin.
- Berikan dokumentasi pada setiap baris kode yang kalian tulis.
"""

#C2K and K2C

#buat rumusnya C ke K, K ke C

def C2K(K):
  return (C + 273)

def K2C(C):
  return (K - 273)

#hitung, tetapin nilai dari C dan K
#panggil function lalu print

C = 400
print("Celcius to Kelvin= ",
      C2K(K))

K = 400
print("Kelvin to Celcius= ",
      K2C(C))

#C2F and K2K

#buat rumusnya C ke F, K ke F

def C2F(C):
  return (C*9/5)+32

def K2F(K):
  return (F-32)*5/9+273

#hitung, tetapin suhu awal C dan K
#panggil function lalu print

C = 400
print("Celcius to Fahrenheit= ",
      C2F(C))

K = 400
print("Kelvin to Fahrenheit= ",
      K2F(K))

#F2C and F2K

#buat rumusnya F ke C, F ke K

def F2C(C):
  return (5/9)*(F-32)

def F2K(K):
  return 273.5 + ((F-32)*(5/9))

#hitung, tetapin suhu awal F yg akan diubah ke C dan K
#panggil function lalu print

F = 400
print("Fahrenheit to Kelvin= ",
      F2C(C))

F = 400
print("Fahrenheit to Celcius= ",
      F2K(K))