# -*- coding: utf-8 -*-
"""NG_Challange1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jr4i7ulGE68RxxAIB1yIOWBa1cf3vdwW
"""

#Loop dan print semua angka genap dari list angka diatas dengan urutan yang sama
#Jangan mencetak angka apa pun yang muncul setelah angka 918.

numbers = [951, 402, 984, 651, 360, 69, 408, 319, 601, 485, 980, 507, 725, 547, 544, 615, 83, 165, 141, 501, 263, 617, 865, 575, 219, 390, 984, 592, 236, 105, 942, 941, 386, 462, 47, 418, 907, 344, 236, 375, 823, 566, 597, 978, 328, 615, 953, 345, 399, 162, 758, 219, 918, 237, 412, 566, 826, 248, 866, 950, 626, 949
  ]

for x in numbers:
  if x == 918:
    print(x)
    break;
  elif x % 2 ==0:
    print(x)
print('done')

#ini out of NG Challange

#Loop dan print semua angka genap dari list angka diatas dengan urutan yang sama
#Jangan mencetak angka apa pun yang muncul setelah angka 918.

numbers = [951, 402, 984, 651, 360, 69, 408, 319, 601, 485, 980, 507, 725, 547, 544, 615, 83, 165, 141, 501, 263, 617, 865, 575, 219, 390, 984, 592, 236, 105, 942, 941, 386, 462, 47, 418, 907, 344, 236, 375, 823, 566, 597, 978, 328, 615, 953, 345, 399, 162, 758, 219, 918, 237, 412, 566, 826, 248, 866, 950, 626, 949
  ]

for i in range(0, len(numbers)):
    for j in range(i+1, len(numbers)):
        if(numbers[i] > numbers[j]):
            temp = numbers[i];
            numbers[i] = numbers[j];
            numbers[j] = temp;

for x in numbers:
  if x == 918:
    print(x)
    break;
  elif x % 2 ==0:
    print(x)
print('done')